name: prox_paper
channels:
  - conda-forge
dependencies:
  - python=3.7.8
  # infrastructure
  - ipython
  # scientific computing
  - numpy=1.19.1
  - scipy=1.5.2
  - matplotlib=3.3.0
  - h5py=2.10.0
  # inference
  - corner=2.0.1
  - emcee=3.0.2
  - dynesty=1.0.0
  # astro
  - astropy=4.0.1

# --- from source ---
# bd-j/sedpy (v0.1.0; 1a20c81)
# cconroy20/fsps (v3.1; d19513ef8)
# dfm/python-fsps (v0.3.0; a1edca9f8)
# bd-j/prospector (0.4.0; fc0c36f)
# bd-j/exspect (05b775b4)
