name: prox
channels:
  - conda-forge
dependencies:
  # infrastructure
  - pip
  - ipython
  # scientific computing
  - numpy
  - scipy
  - matplotlib
  - h5py
  # inference
  - corner
  - emcee
  - dynesty
  # astro
  - astropy
  - pip:
    - astro-sedpy
    - fsps

# --- from source ---
# cconroy20/fsps
# bd-j/prospector
# bd-j/exspect
